music_directory     "/home/tToast/.config/mpd/music"
playlist_directory  "/home/tToast/.config/mpd/playlists"
db_file             "/home/tToast/.config/mpd/mpd.db"
log_file            "/home/tToast/.config/mpd/mpd.log"
pid_file            "/home/tToast/.config/mpd/mpd.pid"
state_file          "/home/tToast/.config/mpd/mpdstate"
auto_update         "yes"
follow_outside_symlinks "yes"
follow_inside_symlinks  "yes"

bind_to_address     "localhost"
port                "6600"

audio_output {
    type        "pulse"
    name        "PipeWire Output"
    mixer_type  "software"
}

